%YAML 1.1
---
# Snapcraft Recipe for GRC's DNS Benchmark
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft

# All following comments, including this one, are designed to be stripped
# before contributing the recipe to the upstream

# GRC's DNS Benchmark, dnsbench, dnsbench-launch
# are placeholders text meant to be replaced by appropriate content
name: dnsbench
title: GRC's DNS Benchmark
summary: A utility to determine the exact performance of DNS nameservers
description: |
  GRC's DNS Benchmark performs a detailed analysis and comparison of the
  operational performance and reliability of any set of up to 200 DNS
  nameservers (sometimes also called resolvers) at once. When the
  Benchmark is started in its default configuration, it identifies all
  DNS nameservers the user's system is currently configured to use and
  adds them to its built-in list of publicly available “alternative”
  nameservers. Each DNS nameserver in the benchmark list is carefully
  “characterized” to determine its suitability — to you — for your use
  as a DNS resolver. This characterization includes testing each
  nameserver for its “redirection” behavior: whether it returns an error
  for a bad domain request, or redirects a user's web browser to a
  commercial marketing-oriented page. While such behavior may be
  acceptable to some users, others may find this objectionable.

  NOTE: This is NOT an official distribution of GRC's DNS Benchmark,
  please refer to the snap's own issue tracker for support:

  Issues · brlin-tw/dnsbench-snap
  https://github.com/brlin-tw/dnsbench-snap/issues

# The path of icon to represent the snap, relative to the source tree directory
# Only PNG or SVG image is supported, dimension must be greater than 256x256px
icon: snap/gui/DNSBench.256px.png

# The license of this application, in SPDX format
# NOTE: Currently only supports SPDX 2.1 license expressions, as described in Appendix IV of
# https://spdx.org/spdx-specification-21-web-version
# Supported expressions:
# https://github.com/snapcore/snapd/blob/HEAD/spdx/licenses.go
# NOTE: Application is a freely to redistribute freeware according to
# the bottom or the Introduction page of the 1.3.6668.0 version of the
# application, quoted as follow:
# "Please Note: This program is Copyright (c) 2010 by Gibson Research
# Corporation -- ALL RIGHTS RESERVED. This program is FREEWARE. Although
# it may not be altered in any way, it MAY BE FREELY COPIED AND
# DISTRIBUTED onto and through any and all computer media in ANY form or
# fashion. You are hereby granted the right to do so."
license: Proprietary

# Version string just for humans, typically '1.2+git' or '1.3.2'
# The wrapping single quotes are often required to avoid the version string
# being accidentally interpreted as a YAML non-string(like '1', '1.2').
# http://yaml.org/type
# https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html#surprising-behaviour
# NOTE: This key is mutual exclusive with the `adopt-info` key
#version: Derived from the part specified by the `adopt-info` property

# Extract metadata from the main snap part
# https://forum.snapcraft.io/t/extracting-information-from-sources-in-snapcraft-parts/4642
adopt-info: main

# Snapd feature set and version the snap requires in order to work
# https://forum.snapcraft.io/t/snapcraft-top-level-metadata/8334#heading--assumes
assumes:
  - command-chain

# Base runtime
# The common runtime for the snap to run on, or `bare` for static linked applications
# https://docs.snapcraft.io/snapcraft-top-level-metadata/8334#heading--base
base: core18

# Wine snaps only buildable on these platforms
architectures:
  - build-on: amd64
  - build-on: i386

# Speed up snap decompression
# How to switch your snap to use LZO compression - snapcraft - snapcraft.io
# https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714
compression: lzo

# Security confinement
# Use `devmode` to getting started
# Flip to `strict` once you have the right plugs and slots,
# or `classic` once you determine that strict confinement is not currently possible
confinement: strict

# Snap Grade
# Use `devel` to getting started
# Flip to `stable` once you determine that the snap is matured, only `stable` grade
# snaps can be promoted to `candidate` and `stable` channels
grade: stable

# Additional metadata
contact: https://github.com/brlin-tw/dnsbench-snap/issues
issues: https://github.com/brlin-tw/dnsbench-snap/issues
source-code: https://github.com/brlin-tw/dnsbench-snap
website: https://github.com/brlin-tw/dnsbench-snap

# Run `snapcraft help sources` for supported keywords on pulling a part's source ingredients
# Run `snapcraft plugins` for supported build helper plugins
# Run `snapcraft help plugins` for supported keywords on building a part
# For `override-*` scriptlets used to modify behavior of certain part's lifecycle phase, check out:
# https://docs.snapcraft.io/scriptlets/4892
parts:
  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*

  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: '1.0'

  main:
    plugin: nil
    build-packages:
      # For extracting the application version
      - binutils

      # For downloading the target executable
      - curl

    override-pull: |
      set -o nounset

      # Fetch portable executable from official website
      curl \
        --location \
        --remote-name \
        https://www.grc.com/files/DNSBench.exe

      # There aren't any reliable version string available from the
      # official website, so we have to extract it from the executable
      upstream_version="$(
        strings \
          --encoding=l \
          DNSBench.exe \
          | grep \
            --perl-regexp \
            '\d+\.\d+\.\d+\.\d+' \
          | head -n1
      )"

      packaging_revision="$(
        git \
          -C "${SNAPCRAFT_PROJECT_DIR}" \
          describe \
          --abbrev=4 \
          --always \
          --match nothing \
          --dirty=-d
      )"

      snap_version_string="${upstream_version}+pkg-${packaging_revision}"

      printf -- \
        'main-adopt-info: Setting snap version to "%s".\n' \
        "${snap_version_string}"
      snapcraftctl set-version \
        "${snap_version_string}"

      override-build: |
        set -o nounset

        install \
          --mode 0644 \
          --verbose \
          DNSBench.exe \
          "${SNAPCRAFT_PART_INSTALL}"/DNSBench.exe

# Apps that are exposed by the snap package
# If the _app_name_ is identical with the _snap_name_ it can be directly run
# with `_snap_name_` or `snap run _snap_name_` commands, otherwise it can only be run
# via `_snap_name_._app_name_` or `snap run _snap_name_._app_name_`
apps:
  dnsbench:
    extensions: [gnome-3-28]
    # The adapter to set up runtime environment at the launch of the snap
    # NOTE: The `command-chain` property is only supported by the `full` adapter
    adapter: full

    # An *relative path* to an executable file root from the `prime` directory to be executed, and its command-line arguments
    # NOTE: The right angle bracket at the beginning of the value of the `command` keyword starts a YAML folded style block scalar, refer the following spec document for more info: http://yaml.org/spec/1.2/spec.html#id2796251
    command: bin/sommelier run-exe

    # The commands that are run, in order, before running the one specified by the `command` key
    command-chain:
      - bin/dnsbench-launch

    environment:
      # Fixes wrong character rendering in "... no official Internet DNS
      # name ..." servers, also seems to fix crash that triggerd when
      # fast-scrolling the name server list
      LANG: en_US

      RUN_EXE: "$SNAP/DNSBench.exe"

      # Prevent pop-ups about Wine Mono and Wine Gecko
      WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="

    plugs: # change these as required
      # Target application plays a sound when loading is finish, etc.
      - audio-playback

      - network

  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network

  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network

# Refer the following documentation for asserting interface plugs and slots in a security confined snap:
# Interface management - doc - snapcraft.io
# https://docs.snapcraft.io/interface-management/6154
# Supported interfaces - doc - snapcraft.io
# https://docs.snapcraft.io/supported-interfaces/7744
# Non-A/C: Non-autoconnect interface
plugs:
  # Network access
  network:

  # This contains all the dependencies Wine needs
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  # This contains the Wine binaries themselves
  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable
